-- MySQL Script generated by MySQL Workbench
-- Mon Apr  7 19:12:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `Biblioteca` ;

-- -----------------------------------------------------
-- Table `Biblioteca`.`Usuários`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Usuários` (
  `IDUsuários` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDUsuários`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Livros` (
  `IDLivro` INT NOT NULL,
  `Título` VARCHAR(45) NOT NULL,
  `Publicação` YEAR(4) NULL,
  `Usuários_IDUsuários` INT NOT NULL,
  PRIMARY KEY (`IDLivro`),
  INDEX `fk_Livros_Usuários1_idx` (`Usuários_IDUsuários` ASC) VISIBLE,
  CONSTRAINT `fk_Livros_Usuários1`
    FOREIGN KEY (`Usuários_IDUsuários`)
    REFERENCES `Biblioteca`.`Usuários` (`IDUsuários`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Autores` (
  `IDAutor` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Autores_has_Livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Autores_has_Livros` (
  `Autores_IDAutor` INT NOT NULL,
  `Livros_IDLivro` INT NOT NULL,
  `Autores_has_Livros` INT NOT NULL,
  PRIMARY KEY (`Autores_IDAutor`, `Livros_IDLivro`, `Autores_has_Livros`),
  INDEX `fk_Autores_has_Livros_Livros1_idx` (`Livros_IDLivro` ASC) VISIBLE,
  INDEX `fk_Autores_has_Livros_Autores1_idx` (`Autores_IDAutor` ASC) VISIBLE,
  CONSTRAINT `fk_Autores_has_Livros_Autores1`
    FOREIGN KEY (`Autores_IDAutor`)
    REFERENCES `Biblioteca`.`Autores` (`IDAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autores_has_Livros_Livros1`
    FOREIGN KEY (`Livros_IDLivro`)
    REFERENCES `Biblioteca`.`Livros` (`IDLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
